# Generated by Django 3.2.7 on 2022-02-27 12:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('name', models.CharField(max_length=40)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='feedback.company')),
            ],
            options={
                'unique_together': {('name', 'company')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeManagement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_iteration', models.CharField(max_length=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_work', to='feedback.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('name', models.CharField(max_length=40)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='feedback.department')),
            ],
            options={
                'unique_together': {('name', 'department')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('positions', models.ManyToManyField(related_name='projects', to='feedback.Position')),
                ('teams', models.ManyToManyField(related_name='projects', to='feedback.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='position',
            name='skills',
            field=models.ManyToManyField(related_name='positions', to='feedback.Skill'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('feedback', models.CharField(max_length=80)),
                ('date', models.DateField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='give_feedback', to='feedback.employee')),
                ('rate_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='feedback.employeemanagement')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='feedback.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='employeemanagement',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filled_position', to='feedback.position'),
        ),
        migrations.AddField(
            model_name='employeemanagement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_info', to='feedback.project'),
        ),
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(related_name='employees', through='feedback.EmployeeManagement', to='feedback.Project'),
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='feedback.team'),
        ),
        migrations.AlterUniqueTogether(
            name='employeemanagement',
            unique_together={('employee', 'project', 'plan_iteration')},
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('first_name', 'last_name')},
        ),
    ]
