# Generated by Django 3.2.7 on 2022-03-07 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20220307_2115'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('feedback', 'skill')},
        ),
    ]
