# Generated by Django 4.0.2 on 2022-05-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20220412_2057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('feedback', 'skill', 'rating')},
        ),
    ]
