# Generated by Django 4.0.2 on 2022-05-09 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('author', 'rate_for')},
        ),
    ]
